const Menu = [
  {
    id: 1,
    image: "images/burger&fries.jpeg",
    name: "burger&fries",
    category: "evening",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 2,
    image: "images/chhole-bhature.jpeg",
    name: "chhole-bhature",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 3,
    image: "images/cupcake.jpeg",
    name: "cupcake",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 4,
    image: "images/maggi.jpeg",
    name: "maggi",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 5,
    image: "images/masaladosa.jpeg",
    name: "masaladosa",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 6,
    image: "images/momo.jpeg",
    name: "momo",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 7,
    image: "images/naan-chicken.jpeg",
    name: "naan-chicken",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 8,
    image: "images/nonvegthali.jpeg",
    name: "nonvegthali",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 9,
    image: "images/panipuri.jpeg",
    name: "panipuri",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 10,
    image: "images/pav-bhaji.jpeg",
    name: "pav-bhaji",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 11,
    image: "images/pizza.jpeg",
    name: "pizza",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 12,
    image: "images/puri-sabzi.jpeg",
    name: "puri-sabzi",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 13,
    image: "images/samosa.jpeg",
    name: "samosa",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 14,
    image: "images/vegthali.jpeg",
    name: "vegthali",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
  {
    id: 15,
    image: "images/sweet.jpeg",
    name: "sweet",
    category: "lunch",
    price: 25,
    description: "I love maggi really Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat magni veniam tenetur provident omnis quae, ea velit at delectus vero.",
  },
];
export default Menu;